### PR TITLE
ignore time when checking min and max dates

### LINKED ISSUE #857: Calendar widget minDate / maxDate interpreted in a wrong way
The calendar widget compares the min/max date with </> instead of <=/=> so it isn't possible to select the current day if it's set as min date.

### PR DESCRIPTION
**Pull request by devpaul**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [x] Unit tests are included in the PR
* [ ] For new widgets, an entry has been added to the `.dojorc`
* [ ] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [ ] WidgetProperties are exported

**Description:**

Updated the Calendar to only take the year, month, and day portions of a date when determining if a day is outside of the min/max dates. Previously it was possible to set a min / max date with a time that would place a day outside of a given range; e.g. if `{ minDate: new Date() }` was used the current day would be outside of the minDate range.

Resolves #857

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-3bbxq7g9a.now.sh
* Tests Deployment: https://dojowidgets-5mnndrx8a.now.sh

File: src/calendar/date-utils.tsx [hunk 1]
```diff
@@ -13,3 +13,11 @@ export function monthInMax(year: number, month: number, maxDate?: Date) {
 	}
 	return true;
 }
+
+function stripTime(date: Date) {
```
Comment (tomdye) [inline src/calendar/date-utils.tsx]: do these need to be in a date-utils file when they're only used in a single location?
