### PR TITLE
Fix slidepane animations with custom theme.

### LINKED ISSUE #129: Slidepane example is broken when the dojo theme is applied
**Bug** 

Package Version: master

**Description**
After the theme split work was completed the slidepane example page does not work correctly when the dojo theme is applied. The pane does not drag open / closed properly.

### PR DESCRIPTION
**Pull request by mwistrand**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Remove direct DOM manipulation from `SlidePane` so that its animations and functionality do not depend directly on `src/slidepane/styles/slidePane.m.css`.

Previously, `SlidePane` treated the `open`, `left`, and `right` CSS classes as fixed classes. However, this made it impossible for themes to specify combinations like `left.slideIn`, since the corresponding `left` class in the generated CSS is different than the fixed class actually applied to the DOM node. As such, `open`, `left`, and `right` were downgraded to normal classes.

Resolves #129

### CODE REVIEW

**Comment by mwistrand** [comment]
@tomdye That would work for the slidepane not closing when the underlay is clicked; I'll update to use a fixed class for that since I guess it is not important/necessary that consumers be able to modify that class. The other changes allow the themed SlidePane to animate opened/closed properly.

**Comment by tomdye** [comment]
Thanks for the clarification @mwistrand . I think that's the better way to go about it.

File: src/slidepane/SlidePane.ts [hunk 1]
```diff
@@ -101,7 +103,7 @@ export default class SlidePane extends SlidePaneBase<SlidePaneProperties> {
 		} = this.properties;
 
 		// Current pointer position
-		const currentX = event.type === 'touchend' ? event.changedTouches[0].screenX : event.pageX;
+		const currentX = type === 'touchend' ? event.changedTouches[0].screenX : event.pageX;
```
Comment (bitpshr) [inline src/slidepane/SlidePane.ts]: If you're going to grab `target` and `type`, might as well destructure fully and grab `changedTouches` too.
