### PR TITLE
Fixed broken Material tab theme

### LINKED ISSUE #1468: Closeable Tabs show `close` text in material theme
**Bug** 

In the material theme, text that reads `close` is visible next to the close icon.
This text should not be visible.

It would appear that the current implementation places the text inside a button then uses an `after` pseudo selector to add the icon then hides the text via `font-size: 0`. 
This should be replaced by a simple `Icon` widget usage with `altText` text reading `close`.

Screenshot 2020-05-13 20 28 15

### PR DESCRIPTION
**Pull request by jellison**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [ ] Unit tests are included in the PR
* [ ] For new widgets, an entry has been added to the `.dojorc`
* [ ] For new widgets, `theme.variant()` is added to the root domnode
* [ ] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [ ] WidgetProperties are exported

**Description:**
Replaced tab "close" with Icon:

Dojo Theme:
image

Material Theme:
image

Resolves #1468

### CODE REVIEW

File: src/theme/material/tab-container.m.css [hunk 1]
```diff
@@ -33,20 +33,13 @@
 	composes: nativeResetRoot from './button.m.css';
 	position: absolute;
 	top: 50%;
-	transform: translateY(-50%);
+	transform: translateY(-50%) scale(0.7);
```
Comment (tomdye) [inline src/theme/material/tab-container.m.css:36]: could a `size` property be specified on the `Icon` instead perhaps?

Comment (jellison) [reply src/theme/material/tab-container.m.css:36]: I considered that, but the Dojo theme doesn't need it. For whatever reason, the Material Icon is just a little big.
