### PR TITLE
Work around VNodeProperties attributes being marked as readonly

### LINKED ISSUE #62: Maquette 2.4.X Regressions
**Bug**

It appears that Maquette 2.4.X has introduced some regressions in our code that was unexpected.  Upon compiling Widgets now we get the following errors:

```
Using tsc v2.0.3
src/mixins/createFormFieldMixin.ts(112,6): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
src/mixins/createFormFieldMixin.ts(115,5): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
src/mixins/createFormFieldMixin.ts(117,6): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
src/mixins/createFormFieldMixin.ts(120,5): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
src/mixins/createRenderMixin.ts(230,6): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
src/mixins/createRenderMixin.ts(231,6): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
src/mixins/createRenderMixin.ts(232,6): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
src/projector.ts(154,5): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
src/projector.ts(160,4): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
src/projector.ts(161,4): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
```

The functional tests also appear to fail, but it is hard to tell if it is related to these complication errors or further breaking changes in Maquette.

Reverting to `maquette@2.3.7` appears to alleviate the problem.

Package Version: 2.0.0-alpha

**Code**

```
> npm install maquette@latest
```

**Expected behavior:**

It works, without issue...

**Actual behavior:**

It has issues.

### PR DESCRIPTION
**Pull request by agubler**
In the latest release of Maquette all the properties of `VNodeProperties` are marked as `readonly` - these changes prevent the regressions noted in issue #62.

We could also maintain a local interface the represents `VNodeProperties` but that might become a pain to maintain (although I added a partial interface for the `projector`, so am open to all suggestions)

resolves #62

### CODE REVIEW

File: src/mixins/createFormFieldMixin.ts [hunk 1]
```diff
@@ -106,20 +106,10 @@ const createFormMixin: FormMixinFactory = compose({
...
-				/* value should always be copied */
-				props.value = this.value;
-				if (this.state && this.state.name) {
-					props.name = this.state.name;
-				}
-
-				props.disabled = Boolean(this.state.disabled);
-
-				return props;
+				return { type, value, name, disabled: Boolean(disabled) };
```
Comment (kitsonk) [inline src/mixins/createFormFieldMixin.ts]: Super 👍

File: src/mixins/createRenderMixin.ts [hunk 2]
```diff
@@ -226,10 +224,7 @@ const createRenderMixin = createStateful
 						widgetClassesMap.set(this, this.classes);
 					}
 
-					props.classes = classes;
-					props.styles = this.styles || {};
-					props.key = this;
-					return props;
+					return Object.assign(baseIdProp, { key: this, classes, styles });
```
Comment (kitsonk) [inline src/mixins/createRenderMixin.ts]: Ideally should use `dojo-core/lang#assign()`.

Comment (agubler) [inline src/mixins/createRenderMixin.ts]: You're absolutely right (failing tests confirm that)!

**Comment by agubler** [comment]
@kit I think it would be prudent to do both, work around in the short/medium term and raise an issue with Maquette highlighting the difficulties "adding" to an existing `VNodeProperties` object.
