### PR TITLE
added fixed classes

### LINKED ISSUE #214: Move purely structural widget styles to use `fixed`
**Enhancement** 

To better support widget theming we should move certain styles / classes to use `this.classes().fixed()` instead.
This avoids the need to replicate structural styles in theme css.

This issue should be used whenever such work is carried out.

### PR DESCRIPTION
**Pull request by tomdye**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Creates `fixed` classes for `Slider` to ease future theming.

Related to  #214

### CODE REVIEW

File: src/slider/Slider.ts [hunk 1]
```diff
@@ -126,7 +126,7 @@ export default class Slider extends SliderBase<SliderProperties> {
 		const outputNode = output ? output(value) : value + '';
 
 		const slider = v('div', {
-			classes: this.classes(css.inputWrapper),
+			classes: this.classes().fixed(css.inputWrapper),
```
Comment (bitpshr) [inline src/slider/Slider.ts]: I've been wondering about situations like this, as I've run into them pretty frequently: should we always provide a themeable class on node's that have a fixed class? It seems odd that our components' themeable classes are only determined by what our default theme necessitates. What if some new theme needs to target `inputWrapper` to satisfy their mock ups, but can't simply because our default theme didn't need a themeable class there?

I don't think this should hold up the PR at all, and I think a pattern will become obvious from community usage and after our own initial theme is done.

**Comment by tomdye** [comment]
@bitpshr The issue is going to remain open to include refactors as and where required. If someone wants to take the time and go through to split these out then then can go for it at some point :)

File: src/slider/Slider.ts (hunk 1 above)
Comment (tomdye) [inline src/slider/Slider.ts]: I think we should only add a themeable class then there's something to be themed. Ie `inputWrapper` does not need a themeable class in this case.

File: src/slider/styles/slider.m.css [hunk 2]
```diff
@@ -31,11 +41,14 @@
 	height: 2em;
 	left: 50%;
 	margin-left: -1em;
-	position: absolute;
 	top: -0.625em;
 	width: 2em;
```
Comment (smhigley) [inline src/slider/styles/slider.m.css]: Should dimensions be under the fixed class? The size of the track and thumb seems like one of the main things someone might want to theme.

Comment (tomdye) [inline src/slider/styles/slider.m.css]: they're not in the fixed class....

Comment (smhigley) [inline src/slider/styles/slider.m.css]: Hah, you're totally right. Sorry! Sneaky line collapsing fooled me 😆
