### PR TITLE
Slider dragging bug

### LINKED ISSUE #328: Slider issue in FireFox
**Bug**

The Slider sometimes doesn't slide when dragged using the mouse in FireFox on OSX.

Package Version: latest

### PR DESCRIPTION
**Pull request by smhigley**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Resolves #328 

Updated theme styles to make the invisible input controls larger. I also added `onChange` in the example page to fix a VO + Safari issue where the visual UI didn't update while interacting with the input.

### CODE REVIEW

File: src/slider/example/index.ts [hunk 1]
```diff
@@ -60,6 +60,7 @@ export class App extends WidgetBase<WidgetProperties> {
 				},
 				step: 1,
 				value: tribbleValue,
+				onChange: this.onTribbleInput,
```
Comment (bitpshr) [inline src/slider/example/index.ts]: Does this mean that both onChange and onInput are required when using this component in certain browsers?

File: src/themes/dojo/slider.m.css [hunk 2]
```diff
@@ -39,20 +39,21 @@
 }
 
 .input {
-	height: var(--border-width);
+	height: 15px;
```
Comment (bitpshr) [inline src/themes/dojo/slider.m.css]: Is this component-specific?

File: src/themes/dojo/variables.css [hunk 3]
```diff
@@ -68,6 +68,7 @@
 	--grid-base: 8px;
 	--spacing-regular: var(--grid-base);
 	--spacing-large: calc(var(--grid-base) * 2);
+	--touch-target-min: 48px;
```
Comment (bitpshr) [inline src/themes/dojo/variables.css]: You could base this on `--grid-base` like other derived variables.

File: src/themes/dojo/slider.m.css (hunk 2 above)
Comment (smhigley) [reply src/themes/dojo/slider.m.css]: yeah, I just picked a number that seemed big enough. I'm not sure what variable it would be / if it should even be a variable

File: src/themes/dojo/variables.css (hunk 3 above)
Comment (smhigley) [reply src/themes/dojo/variables.css]: I considered it, but I think it's actually an independent pixel value in its own right, based on recommendations for minimum touch target sizes. If it were based on `--grid-size`, that would imply it could change if you changed the grid base, whereas I think it should always stay the same

File: src/slider/example/index.ts (hunk 1 above)
Comment (bitpshr) [reply src/slider/example/index.ts]: (we chatted about this, only for VO + Safari)

**Comment by bitpshr** [comment]
🚢

File: src/slider/example/index.ts (hunk 1 above)
Comment (smhigley) [reply src/slider/example/index.ts]: I need to remember to file a bug report with VoiceOver :P
