### PR TITLE
fix: convert RangeSlider to functional widget

### LINKED ISSUE #1028: Align existing input widgets with the `initialValue` pattern
## Enhancement

For all new input / form widgets we have implemented a pattern whereby they no longer take a controlled `value` property and instead take `initialValue`. From then on, the input will maintain and display it's own value, passing back any changes via `onValue`.

We should ensure that all existing widgets use this pattern.

### LINKED ISSUE #1147: Convert Range slider to function based and accept initialValue
Range slider should accept an `initialValue` and use the `icache` to manage it's state as per other form widgets. This will require converting it to being function based.

### PR DESCRIPTION
**Pull request by bitpshr**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [x] Unit tests are included in the PR
* [x] For new widgets, an entry has been added to the `.dojorc`
* [x] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [x] WidgetProperties are exported

**Description:**

This pull request updates `RangeSlider` to be a functional widget, updates its tests to use assertion templates, and updates its internal logic to use the new `initialValue` pattern.

Resolves #1028
Resolves #1147

**Preview:**

preview

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-61d08p89p.now.sh
* Tests Deployment: https://dojowidgets-8awmir2wa.now.sh

File: src/range-slider/index.tsx [hunk 1]
```diff
@@ -63,281 +62,253 @@ export interface RangeSliderProperties extends ThemedProperties {
...
-		);
+	if (
+		!existingInitialValue ||
+		initialValue.min !== existingInitialValue.min ||
+		initialValue.max !== existingInitialValue.max
+	) {
+		icache.set('value', initialValue);
+		icache.set('initialValue', initialValue);
+		value = initialValue;
+		onValue && onValue(initialValue);
```
Comment (tomdye) [inline src/range-slider/index.tsx]: why are you calling `onValue` here? I've noticed we're doing this elsewhere too but i'm not sure why.

File: src/range-slider/index.tsx [hunk 2]
```diff
@@ -63,281 +62,253 @@ export interface RangeSliderProperties extends ThemedProperties {
...
+				themeCss.root,
+				disabled ? themeCss.disabled : null,
+				focus.isFocused('root') ? themeCss.focused : null,
+				valid === false ? themeCss.invalid : null,
+				valid === true ? themeCss.valid : null,
+				readOnly ? themeCss.readonly : null,
+				showOutput ? themeCss.hasOutput : null
+			]}
+		>
+			{labelAfter ? children.reverse() : children}
```
Comment (tomdye) [inline src/range-slider/index.tsx]: we've dropped `labelAfter`, I don't think we want it here anymore either, label should go above.

File: src/range-slider/index.tsx (hunk 1 above)
Comment (bitpshr) [reply src/range-slider/index.tsx]: If a consumer sets a new `initialValue` on this widget, this condition will be triggered. I think `onValue` is called here since the new `initialValue` will in turn result in a new internal `value` being set. Even though it's not technically needed, it would feel odd if this didn't trigger `onValue`, but all other internal value changes did.

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-jefgpya64.now.sh
* Tests Deployment: https://dojowidgets-3ozgpe320.now.sh

File: src/range-slider/index.tsx (hunk 1 above)
Comment (tomdye) [reply src/range-slider/index.tsx]: i'm not sure we need to call `onValue` as the value was just set, could easily cause a loop

Comment (bitpshr) [reply src/range-slider/index.tsx]: Updated.

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-nq4b159qy.now.sh
* Tests Deployment: https://dojowidgets-6zu2d72oz.now.sh
