### PR TITLE
fix: correctly validate required TimePicker

### LINKED ISSUE #1714: When using the Form the TimePicker is reported as valid even when the form field is required
**Bug**

When using the form widget and configuring a field to be "required" it should the whole form should only be valid once the input has been populated. The `TimePicker` reports as valid and therefore the forms valid state is set to true even though the required form as not been populated.

Codesandbox example: https://codesandbox.io/s/practical-solomon-wdysh?file=/src/main.tsx

### PR DESCRIPTION
**Pull request by bitpshr**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [ ] Unit tests are included in the PR
* [x] For new widgets, an entry has been added to the `.dojorc`
* [x] For new widgets, `theme.variant()` is added to the root domnode
* [x] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [x] WidgetProperties are exported

**Description:**

This pull request fixes an issue with `TimePicker` that prevented required instances from failing validation.

Resolves #1714

### CODE REVIEW

File: src/time-picker/index.tsx [hunk 1]
```diff
@@ -335,7 +335,7 @@ export const TimePicker = factory(function TimePicker({
 				}
 			}
 
-			isValid = validationMessages.length === 0;
+			isValid = isValid === undefined ? validationMessages.length === 0 : isValid;
```
Comment (bitpshr) [inline src/time-picker/index.tsx:338]: This was the root of the issue: The underlying `TextInput` updates `inputIsValid`, but then local validation and `validationMessages.length` ended up overwriting this before triggering `onValidate`.

**Comment by tomdye** [comment]
@bitpshr should this be showing as visibly valid, ie. green, when set to required and with a value passed? It appears that it currently does not. Also, it looks like the dojo themed time picker now shows as valid / green as soon as it is rendered even though it's not supposed to.

**Comment by bitpshr** [comment]
@tomdye: The Material `TimePicker` does not show any valid border in its valid state (and neither do any other inputs, like `TextInput`), so I think we're good there. The Dojo `TimePicker` always showed a green border when initially rendered, and that is not related to these changes, but I can take a look at that as part of this PR.

**Review by agubler — CHANGES_REQUESTED** [review]
This works for me, I'd like to get @tomdye's approval and also a test to cover the changes?

**Comment by bitpshr** [comment]
@agubler test added that fails on `master` and passes here, made as simple as possible to show the issue. cc sir @tomdye when you have a chance to sign off.

File: src/time-picker/tests/unit/TimePicker.spec.tsx [hunk 2]
```diff
@@ -65,32 +65,33 @@ const baseTemplate = (date?: Date) =>
...
-				type="text"
-				variant={undefined}
-				classes={undefined}
-			>
-				{{ label: undefined, trailing: undefined }}
-			</TextInput>
-		</div>
-	);
-});
+const buttonTemplate = (required?: boolean) =>
```
Comment (tomdye) [inline src/time-picker/tests/unit/TimePicker.spec.tsx:68]: test looks good, but we've tried really hard to remove any need for these `getRender` / `getTemplate` functions via the addition of the assertion template so I'd rather we didn't add one here when you could simply to

```
const requiredTemplate = baseTemplate
			.setProperty('@input', 'required', true)
```

**Review by tomdye — APPROVED** [review]
Added a comment re. how `setProperty` should be used on the `baseTemplate`, once that's fixed please merge
