### PR TITLE
fix: paginated grid row selection

### LINKED ISSUE #1436: Dojo Grid returning incorrect details from 2nd page onwards
**Bug / Enhancement** 
Dojo Grid returns the incorrect selected data from 2nd page onward
The bug can be reproducible here - https://dist-5qhc8bqm4.now.sh/
select any row in first page and go to next page and click on any row and notice the grid is not returning the selected row details instead returning row details always from first page.

Package Version: 6.2.0
**Code**
click here for source code -  
(https://github.com/dojo/framework/files/4545461/dojoGrid_src_code.zip)

Click here for explanation about the bug   
(https://github.com/dojo/framework/files/4545460/Dojo.Grid.Issues.docx)

**Expected behavior:**

Grid should return the selected row details

**Actual behavior:**

Grid returns always the details from page 1

### PR DESCRIPTION
**Pull request by bitpshr**
**Type:** bugfix

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [x] Unit tests are included in the PR
* [x] For new widgets, an entry has been added to the `.dojorc`
* [x] For new widgets, `theme.variant()` is added to the root domnode
* [x] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [x] WidgetProperties are exported

**Description:**

This pull request updates the `Grid` widget by fixing a bug in paginated grids that prevented row selection from working properly.

Resolves #1436 

**Preview:**

preview

### CODE REVIEW

File: src/grid/index.tsx [hunk 1]
```diff
@@ -1,31 +1,31 @@
...
-	selectionProcess
+	updaterProcess
 } from './processes';
-
-import Header, { SortRenderer, FilterRenderer } from './Header';
-import Body from './Body';
-import Footer from './Footer';
-import PaginatedFooter from './PaginatedFooter';
-import PaginatedBody from './PaginatedBody';
-import * as css from '../theme/default/grid.m.css';
```
Comment (bitpshr) [inline src/grid/index.tsx:28]: This is churn from [sort-imports](https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports). Sorry about the noise.

File: src/grid/index.tsx [hunk 2]
```diff
@@ -1,31 +1,32 @@
...
```
Comment (bitpshr) [inline src/grid/index.tsx:28]: This is churn from [sort-imports](https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports). Sorry about the noise.

File: src/grid/index.tsx [hunk 3]
```diff
@@ -164,7 +165,10 @@ export default class Grid<S> extends I18nMixin(ThemedMixin(WidgetBase))<GridProp
 	}
 
 	private _pageChange(page: number) {
-		const { storeId } = this._getProperties();
+		const { pagination, storeId } = this._getProperties();
+		if (pagination) {
+			clearSelectionProcess(this._store)({ id: storeId });
+		}
```
Comment (bitpshr) [inline src/grid/index.tsx:171]: This removes selection when changing pages on paginated grids. This was an issue also reported on #1436.
